### ISSUE TITLE
Users Command permission add not working

### ISSUE THREAD

**Issue by einrobin** [CloudNetService/CloudNet-v2#219]
When typing "user permission add NAME PERMISSION", an UnsupportedOperationException occurs: https://pastes.gq/48ek1Gl90z the user was just created using "create user NAME PASSWORD", it works when using "user create NAME PASSWORD"

**Comment by GiantTreeLP** [comment]
I can confirm, this happens, due to the fact, that the permissions are an empty array as a list.

https://github.com/CloudNetService/CloudNet/blob/8a225fb6cba21d288d420968fc228ea6cde5d720/cloudnet-core/src/main/java/de/dytanic/cloudnetcore/command/CommandCreate.java#L117

Due to the fact, that the `user` command covers all management about users, we should remove the `create user` command.
